### PR TITLE
#33: Fix trigger if table contains column with non-equality type for ignore_unchanged_values=false

### LINKED ISSUE #33: Trigger not working if table contains column with non-equality type
If the table contains a column which does not implement equality operator then the versioning trigger fails. The equality operator is not implemented for some PostGIS data types, JSON data types, etc.

Example error for table with PostGIS **polygon** type:
```
ERROR:  could not identify an equality operator for type polygon
CONTEXT:  PL/pgSQL function versioning() line 38 at IF
```

The reason is the `NEW IS NOT DISTINCT FROM OLD` statement in IF condition related to the **ignore_unchanged_values** feature. The failure occurs even if the **ignore_unchanged_values** is not enabled as all parts of the IF condition are executed. Thus the issue is quite severe as it breaks compatibility/functionality with the old fashion temporal_tables.

### PR DESCRIPTION
**Pull request by dzolo**
Fixes #33

### CODE REVIEW

**Comment by simoneb** [comment]
@paolochiodi can you take a look at this when you have a chance?

**Comment by wshart** [comment]
@paolochiodi Is there any chance this could be merged soon? I have a use-case for which the original issue would make this package a non-starter

**Comment by simoneb** [comment]
@dzolo thanks for your PR and apologies for the lack of feedback. Is there a chance you can try resolving the merge conflicts in your branch? If you don't have capacity, I can try to do that instead.

**Review by simoneb — APPROVED** [review]
Amazing thank you 🚀

**Comment by wshart** [comment]
Thank you both!

**Pull request merged**
