### PR TITLE
Parameter to ignore unchanged values

### PR DESCRIPTION
**Pull request by ps2goat**
I can update other files to match this new functionality if you comment with your approval.

This takes an optional fourth parameter. If it equates to true, and an update is being performed, this will verify that _something_ is different between the two rows before copying to the history table.

### CODE REVIEW

**Comment by ps2goat** [comment]
Proposed new feature in issue #10

**Comment by ps2goat** [comment]
Any feedback on this?

**Comment by AntonAkovP** [comment]
@paolochiodi will you take a look at this please

**Comment by PMLP-novo** [comment]
Could be nice if this was added to the versioning_no_checks_function as well

**Comment by glennr** [comment]
@ps2goat - perhaps some unit tests would speed the merge of this?

**Comment by paolochiodi** [comment]
@PMLP-novo @ps2goat I have a new PR that includes these commits and adds tests: https://github.com/nearform/temporal_tables/pull/20

I expect to merge it soon

**Pull request merged**
